# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(verbose_name='Comments'),
        ),
    ]
