# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151227_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unapproved', 'Unapproved'), ('spammed', 'Spammed')], default='unapproved', max_length=10),
        ),
    ]
