# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unapproved', 'Unapproved'), ('spammed', 'Spammed'), ('deleted', 'Deleted')], default='unapproved', max_length=10),
        ),
    ]
